# Generated by Django 6.0.4 on 2026-04-12 20:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('udg_code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('udg_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\+?\\d{7,15}$', 'Número de teléfono inválido')])),
                ('current_semester', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
                ('admission_year', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2026)])),
                ('udg_calendar', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('situation', models.CharField(choices=[('ACTIVO', 'Activo'), ('GRADUADO', 'Graduado'), ('BAJA', 'Baja'), ('INACTIVO', 'Inactivo'), ('DESCONOCIDO', 'Desconocido')], default='DESCONOCIDO', max_length=20)),
            ],
        ),
    ]
