# Generated by Django 6.0.4 on 2026-04-12 22:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogdemo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('udg_code', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Código de profesor UDG')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('udg_email', models.EmailField(blank=True, max_length=254, verbose_name='Correo UDG')),
                ('tutoring_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='last_job',
            field=models.TextField(blank=True, verbose_name='Ult. lugar de trabajo'),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_year',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2026)], verbose_name='Año de admisión'),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_semester',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='Semestre en curso'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\+?\\d{7,15}$', 'Número de teléfono inválido')], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='student',
            name='situation',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('GRADUADO', 'Graduado'), ('BAJA', 'Baja'), ('INACTIVO', 'Inactivo'), ('DESCONOCIDO', 'Desconocido')], default='DESCONOCIDO', max_length=20, verbose_name='Situación del estudiante'),
        ),
        migrations.AlterField(
            model_name='student',
            name='udg_calendar',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1, verbose_name='Calendario'),
        ),
        migrations.AlterField(
            model_name='student',
            name='udg_code',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Código de estudiante UDG'),
        ),
        migrations.AlterField(
            model_name='student',
            name='udg_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo UDG'),
        ),
    ]
