# Generated by Django 6.0.4 on 2026-04-12 22:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogdemo', '0002_professor_student_last_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_year',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2026)], verbose_name='Año de admisión'),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_semester',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='Semestre en curso'),
        ),
        migrations.AlterField(
            model_name='student',
            name='situation',
            field=models.CharField(blank=True, choices=[('ACTIVO', 'Activo'), ('GRADUADO', 'Graduado'), ('BAJA', 'Baja'), ('INACTIVO', 'Inactivo'), ('DESCONOCIDO', 'Desconocido')], default='DESCONOCIDO', max_length=20, verbose_name='Situación del estudiante'),
        ),
        migrations.AlterField(
            model_name='student',
            name='udg_calendar',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B')], max_length=1, verbose_name='Calendario'),
        ),
    ]
