# Generated by Django 6.0.4 on 2026-04-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogdemo', '0003_alter_student_admission_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='tutoring_number',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
