# Generated by Django 6.0.4 on 2026-04-12 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogdemo', '0004_alter_professor_tutoring_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('TUTOR1', 'Tutor 1'), ('TUTOR2', 'Tutor 2'), ('TUTOR3', 'Tutor 3')], max_length=10)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blogdemo.professor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blogdemo.student')),
            ],
            options={
                'unique_together': {('student', 'role')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='tutors',
            field=models.ManyToManyField(related_name='students', through='blogdemo.StudentTutor', to='blogdemo.professor'),
        ),
    ]
