# Generated by Django 6.0.4 on 2026-04-12 23:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogdemo', '0005_studenttutor_student_tutors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='situation',
            field=models.CharField(blank=True, choices=[('ACTIVO', 'Activo'), ('GRADUADO', 'Graduado'), ('BAJA', 'Baja'), ('INACTIVO', 'Inactivo'), ('DESCONOCIDO', 'Desconocido')], max_length=20, verbose_name='Situación del estudiante'),
        ),
        migrations.CreateModel(
            name='ConacytScholarship',
            fields=[
                ('conacyt_id', models.CharField(max_length=15, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{4,15}$', 'ID de beca inválido')], verbose_name='ID Beca Conacyt')),
                ('start_date', models.DateField(blank=True, verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, verbose_name='Fecha de finalización')),
                ('status', models.CharField(choices=[('BAJA', 'Baja'), ('SIN BECA', 'Sin Beca')], max_length=10, verbose_name='Estatus')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship', to='blogdemo.student')),
            ],
        ),
    ]
