# Generated by Django 6.0.4 on 2026-04-12 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogdemo', '0006_alter_student_situation_conacytscholarship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conacytscholarship',
            name='status',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('BAJA', 'Baja'), ('SIN BECA', 'Sin Beca')], max_length=10, verbose_name='Estatus'),
        ),
    ]
