# Generated by Django 6.0.4 on 2026-04-13 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogdemo', '0007_alter_conacytscholarship_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lgca', models.CharField(max_length=255, verbose_name='LGCAs')),
                ('title', models.TextField(blank=True, verbose_name='Titulo de tesis')),
                ('graduation_date', models.DateField(blank=True, verbose_name='Fecha de graduación')),
                ('record', models.CharField(blank=True, max_length=10, verbose_name='Acta de tesis')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thesis', to='blogdemo.student')),
            ],
        ),
    ]
