# Generated by Django 6.0.4 on 2026-04-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogdemo', '0008_thesis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='graduation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de graduación'),
        ),
    ]
