# Generated by Django 6.0.4 on 2026-04-13 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogdemo', '0009_alter_thesis_graduation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThesisProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('DIRECTOR', 'Director'), ('CO_DIRECTOR', 'Co-director'), ('ASESOR_CO_DIRECTOR', 'Asesor Co-director'), ('ASESOR', 'Asesor')], max_length=20)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogdemo.professor')),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogdemo.thesis')),
            ],
            options={
                'unique_together': {('thesis', 'role')},
            },
        ),
        migrations.AddField(
            model_name='thesis',
            name='professors',
            field=models.ManyToManyField(related_name='thesis', through='blogdemo.ThesisProfessor', to='blogdemo.professor'),
        ),
    ]
